import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { Store } from '../server/store.mjs';
import { fixture, futureMoscow, signedContact } from './helpers.mjs';

const banquet = restaurantId => ({ title: 'Корпоратив', restaurantId, date: futureMoscow(14), deadline: futureMoscow(10), expectedGuests: 5 });

test('banquet organizers have full rights only for assigned events; access list hides unrelated users', async t => {
  const f = await fixture(t, { openOrganizerSignup: false });
  const root = await f.login(900, 'Администратор');
  const owner = await f.login(300, 'Ольга');
  const delegate = await f.login(400, 'Пётр');
  const outsider = await f.login(500, 'Чужой');
  const restaurants = (await f.request('/api/restaurants', { token: owner.token })).data;
  const first = restaurants[0];
  assert.ok(restaurants.length >= 2);
  const guestRestaurants = (await f.request('/api/restaurants', { token: outsider.token })).data;
  assert.deepEqual(guestRestaurants.map(restaurant => restaurant.id), restaurants.map(restaurant => restaurant.id));
  assert.ok(guestRestaurants.every(restaurant => restaurant.access === null));
  assert.equal(first.access, null);
  assert.equal((await f.request(`/api/restaurants/${first.id}/menu`, { token: owner.token, method: 'POST', body: {} })).status, 403);
  assert.equal((await f.request(`/api/restaurants/${first.id}/menu`, { token: outsider.token, method: 'POST', body: {} })).status, 403);
  const created = await f.request('/api/events', { token: owner.token, method: 'POST', body: banquet(first.id) });
  assert.equal(created.status, 201);
  const event = created.data;
  assert.equal(event.canManage, true);
  assert.equal((await f.request('/api/events', { token: delegate.token })).data.length, 0);
  const before = (await f.request('/api/users', { token: root.token })).data;
  assert.ok(before.some(user => user.id === owner.user.id));
  assert.ok(!before.some(user => user.id === outsider.user.id));
  assert.ok(!before.some(user => user.id === delegate.user.id));
  assert.equal((await f.request(`/api/events/${event.id}/organizers/phone:+79990000400`, { token: owner.token, method: 'PUT', body: { enabled: true } })).status, 200);
  const bound = await f.request('/api/me/phone', { token: delegate.token, method: 'PUT', body: signedContact(400, '+79990000400') });
  assert.equal(bound.status, 200);
  const delegated = (await f.request(`/api/events/${event.id}`, { token: delegate.token })).data;
  assert.equal(delegated.event.canManage, true);
  assert.equal(delegated.canSelect, true);
  assert.equal((await f.request(`/api/events/${event.id}/selection`, { token: delegate.token, method: 'PUT', body: { items: [{ menuItemId: delegated.menu[0].id, quantity: 1 }] } })).status, 200);
  assert.equal((await f.request('/api/kitchen', { token: delegate.token })).status, 403);
  assert.equal((await f.request(`/api/events/${event.id}/organizers/max:500`, { token: delegate.token, method: 'PUT', body: { enabled: true } })).status, 200);
  assert.equal((await f.request(`/api/events/${event.id}/organizers`, { token: owner.token })).data.length, 3);
  assert.equal((await f.request('/api/users', { token: delegate.token })).status, 200);
  assert.equal((await f.request(`/api/events/${event.id}/organizers/max:500`, { token: owner.token, method: 'DELETE' })).status, 200);
  assert.equal((await f.request(`/api/events/${event.id}`, { token: outsider.token })).status, 404);
});

test('service administrator grants restaurant admins by MAX ID while guests can join by verified phone', async t => {
  const f = await fixture(t, { openOrganizerSignup: false });
  const root = await f.login(900);
  const first = (await f.request('/api/restaurants', { token: root.token })).data[0];
  assert.equal((await f.request(`/api/restaurants/${first.id}/members/max:200`, { token: root.token, method: 'PUT', body: { role: 'admin' } })).status, 200);
  const scoped = await f.login(200);
  assert.equal(scoped.user.role, 'restaurant');
  assert.equal((await f.request(`/api/restaurants/${first.id}/members/max:300`, { token: scoped.token, method: 'PUT', body: { role: 'admin' } })).status, 403);
  const owner = await f.login(300);
  const event = await f.event(owner.token);
  assert.equal((await f.request(`/api/events/${event.id}`, { token: scoped.token })).status, 200);
  const guest = await f.login(400);
  assert.equal((await f.request(`/api/invites/${event.inviteCode}/join`, { token: guest.token, method: 'POST' })).status, 403);
  assert.equal((await f.request('/api/me/phone', { token: guest.token, method: 'PUT', body: signedContact(400, '+79990000400') })).status, 200);
  assert.equal((await f.request(`/api/invites/${event.inviteCode}/join`, { token: guest.token, method: 'POST' })).status, 200);
  assert.equal((await f.request(`/api/events/${event.id}`, { token: guest.token })).data.canSelect, true);
});

test('only a restaurant administrator may delete an approved banquet', async t => {
  const f = await fixture(t);
  const serviceAdmin = await f.login(900);
  const organizer = await f.login(300);
  const restaurantAdmin = await f.login(200);
  const restaurant = (await f.request('/api/restaurants', { token: serviceAdmin.token })).data[0];
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/members/max:200`, { token: serviceAdmin.token, method: 'PUT', body: { role: 'admin' } })).status, 200);
  const created = await f.request('/api/events', { token: organizer.token, method: 'POST', body: banquet(restaurant.id) });
  assert.equal(created.status, 201);
  assert.equal(created.data.canDelete, true);
  f.store.db.prepare("UPDATE events SET status='approved', approved_at=? WHERE id=?").run(new Date().toISOString(), created.data.id);
  const organizerEvent = (await f.request(`/api/events/${created.data.id}`, { token: organizer.token })).data.event;
  const adminEvent = (await f.request(`/api/events/${created.data.id}`, { token: restaurantAdmin.token })).data.event;
  assert.equal(organizerEvent.canManage, true);
  assert.equal(organizerEvent.canDelete, false);
  assert.equal(adminEvent.canDelete, true);
  const denied = await f.request(`/api/events/${created.data.id}`, { token: organizer.token, method: 'DELETE' });
  assert.equal(denied.status, 403);
  assert.match(denied.data.error, /После утверждения.*администратор ресторана/);
  assert.equal((await f.request(`/api/events/${created.data.id}`, { token: restaurantAdmin.token, method: 'DELETE' })).status, 200);
});

test('catalog selector can keep, remove and restore dishes atomically', async t => {
  const f = await fixture(t);
  const owner = await f.login(100);
  const event = await f.event(owner.token);
  const itemIds = event.menu.map(item => item.id);
  const path = `/api/events/${event.id}/menu/catalog`;
  assert.equal((await f.request(path, { token: owner.token, method: 'PUT', body: { itemIds } })).status, 200);
  const reduced = await f.request(path, { token: owner.token, method: 'PUT', body: { itemIds: itemIds.slice(1) } });
  assert.equal(reduced.status, 200);
  assert.equal(reduced.data.removed, 1);
  assert.ok(!(await f.request(`/api/events/${event.id}`, { token: owner.token })).data.menu.some(item => item.id === itemIds[0]));
  const restored = await f.request(path, { token: owner.token, method: 'PUT', body: { itemIds } });
  assert.equal(restored.status, 200);
  assert.equal(restored.data.added, 1);
  assert.equal((await f.request(`/api/events/${event.id}/selection`, { token: owner.token, method: 'PUT', body: { items: [{ menuItemId: itemIds[0], quantity: 1 }] } })).status, 200);
  const blocked = await f.request(path, { token: owner.token, method: 'PUT', body: { itemIds: itemIds.slice(1) } });
  assert.equal(blocked.status, 409);
  assert.match(blocked.data.error, /уже выбрали гости/);
  assert.ok((await f.request(`/api/events/${event.id}`, { token: owner.token })).data.menu.some(item => item.id === itemIds[0]));
});

test('kitchen board exports CSV and a valid XLSX workbook, also through a one-use link', async t => {
  const f = await fixture(t);
  const admin = await f.login(900, 'Шеф');
  const owner = await f.login(100);
  const guest = await f.login(200, '=Гость');
  const event = await f.event(owner.token);
  await f.inviteGuest(owner.token, event, guest.token, 200, '+79990000002', '=Гость');
  await f.request(`/api/events/${event.id}/selection`, { token: guest.token, method: 'PUT', body: { items: [{ menuItemId: event.menu[2].id, quantity: 2 }], notes: 'Без лука' } });
  await f.request(`/api/events/${event.id}/shared`, { token: owner.token, method: 'PUT', body: { items: [{ menuItemId: event.menu[0].id, quantity: 3 }] } });
  assert.equal((await f.request('/api/kitchen/export?format=csv', { token: owner.token })).status, 403);
  assert.equal((await f.request('/api/kitchen/export?format=pdf', { token: admin.token })).status, 400);
  const csv = await f.request('/api/kitchen/export?format=csv', { token: admin.token });
  assert.equal(csv.status, 200);
  assert.match(csv.headers.get('content-disposition'), /kitchen-\d{4}-\d{2}-\d{2}\.csv/);
  assert.ok(csv.data.includes(`"${event.menu[0].name}";"3";"3"`));
  assert.ok(csv.data.includes(`"'=Гость"`) && csv.data.includes('"Без лука"'));

  const link = await f.request('/api/kitchen/export-link', { token: admin.token, method: 'POST', body: { format: 'xlsx' } });
  const url = new URL(link.data.url);
  const file = await fetch(f.base + url.pathname);
  assert.equal(file.headers.get('content-type'), 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  const bytes = Buffer.from(await file.arrayBuffer());
  assert.equal((await fetch(f.base + url.pathname)).status, 404, 'link works once');
  const directory = await mkdtemp(join(tmpdir(), 'xlsx-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  await writeFile(join(directory, 'k.xlsx'), bytes);
  const listing = execFileSync('unzip', ['-l', join(directory, 'k.xlsx')], { encoding: 'utf8' });
  assert.match(listing, /xl\/worksheets\/sheet2\.xml/);
  const sheet = execFileSync('unzip', ['-p', join(directory, 'k.xlsx'), 'xl/worksheets/sheet2.xml'], { encoding: 'utf8' });
  assert.match(sheet, /=Гость/, 'xlsx keeps text cells as text, formulas are not created');
  assert.match(sheet, /Без лука/);
  const workbook = execFileSync('unzip', ['-p', join(directory, 'k.xlsx'), 'xl/workbook.xml'], { encoding: 'utf8' });
  assert.match(workbook, /name="Рассадка"/);
  assert.match(workbook, /name="Пакеты"/);
});

test('v8 migration turns the old organizer list and banquet owners into restaurant access', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'access-migration-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const config = { databasePath: join(directory, 'db.sqlite'), demoEnabled: true, restaurantAdminIds: [], publicUrl: 'https://banquet.example', maxDemoSpaces: 10 };
  const store = new Store(config);
  const restaurant = store.db.prepare("SELECT id FROM restaurants WHERE scope='live'").get().id;
  store.db.exec(`INSERT INTO users (id,scope,external_id,name,role,demo,phone,phone_verified_at) VALUES ('max_1','live','1','Ольга','organizer',0,'79990000001',1), ('max_2','live','2','Иван','organizer',0,NULL,NULL);
    CREATE TABLE organizers (id TEXT PRIMARY KEY, scope TEXT, name TEXT, phone TEXT, created_at TEXT);
    INSERT INTO organizers VALUES ('o1','live','Ольга','79990000001','2026-01-01');
    INSERT INTO events (id,scope,owner_id,restaurant_id,title,date,deadline,expected_guests,budget,invite_code,created_at) VALUES ('e1','live','max_2','${restaurant}','Старый','2027-01-01T00:00:00.000Z','2026-12-01T00:00:00.000Z',5,0,'aaaaaaaaaaaaaaaaaaaaaaaa','2026-01-01');
    PRAGMA user_version = 7;`);
  store.close();
  const migrated = new Store(config);
  t.after(() => migrated.close());
  assert.deepEqual(migrated.db.prepare('SELECT user_id FROM event_organizers WHERE event_id=? ORDER BY user_id').all('e1').map(row => row.user_id), ['max_1', 'max_2']);
  assert.equal(migrated.db.prepare("SELECT 1 FROM sqlite_master WHERE name='organizers'").get(), undefined);
  assert.equal(new DatabaseSync(config.databasePath).prepare('PRAGMA user_version').get().user_version, 15);
});

test('a live organizer orders and picks a seat at their own banquet without being on the guest list', async t => {
  const f = await fixture(t, { openOrganizerSignup: false });
  const root = await f.login(900, 'Суперадмин');
  const owner = await f.login(300, 'Ольга');
  const stranger = await f.login(400, 'Пётр');
  const [restaurant] = (await f.request('/api/restaurants', { token: root.token })).data;
  await f.request(`/api/restaurants/${restaurant.id}/members/${owner.user.id}`, { token: root.token, method: 'PUT', body: { role: 'organizer' } });
  const event = (await f.request('/api/events', { token: owner.token, method: 'POST', body: banquet(restaurant.id) })).data;
  const detail = (await f.request(`/api/events/${event.id}`, { token: owner.token })).data;
  assert.equal(detail.canSelect, true);
  assert.equal(detail.event.canManage, true);
  const dish = detail.menu[2];
  assert.equal((await f.request(`/api/events/${event.id}/selection`, { token: owner.token, method: 'PUT', body: { items: [{ menuItemId: dish.id, quantity: 1 }] } })).status, 200);
  assert.equal((await f.request(`/api/events/${event.id}/selection`, { token: stranger.token, method: 'PUT', body: { items: [{ menuItemId: dish.id, quantity: 1 }] } })).status, 403);
  await f.request(`/api/events/${event.id}/seating`, { token: owner.token, method: 'PUT', body: { mode: 'choice', layout: { tables: [{ id: 't1', shape: 'round', label: '1', x: 0, y: 0, w: 120, h: 120, rotation: 0, seats: 4 }] } } });
  assert.equal((await f.request(`/api/events/${event.id}/seat`, { token: owner.token, method: 'PUT', body: { seatId: 't1-1' } })).data.mySeat, 't1-1');
  const after = (await f.request(`/api/events/${event.id}`, { token: owner.token })).data;
  assert.equal(after.event.responded, 1);
  assert.equal(after.guests[0].name, 'Ольга Тестовая');
  const revision = after.event.revision;
  assert.equal((await f.request(`/api/events/${event.id}/approve`, { token: owner.token, method: 'POST', body: { expectedRevision: revision } })).data.status, 'approved');
});
