import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './helpers.mjs';
import { generateLayout, validateLayout } from '../shared/seating.mjs';

const atNoon = days => {
  const day = new Date(Date.now() + days * 86400000).toLocaleDateString('sv-SE', { timeZone: 'Europe/Moscow' });
  return new Date(`${day}T12:00:00+03:00`).toISOString();
};
const plusHours = (value, hours) => new Date(Date.parse(value) + hours * 3600000).toISOString();

test('hall bookings reject overlap, allow back-to-back and parallel halls, and enforce capacity/windows', async t => {
  const f = await fixture(t);
  const admin = await f.login(900);
  const owner = await f.login(100);
  const restaurant = (await f.request('/api/restaurants', { token: owner.token })).data[0];
  const date = atNoon(14), deadline = atNoon(10);
  const body = { title: 'Первый банкет', restaurantId: restaurant.id, hallId: restaurant.halls[0].id, date, deadline, durationHours: 4, expectedGuests: 12, seating: { mode: 'choice', template: 'rounds' } };
  const first = await f.request('/api/events', { token: owner.token, method: 'POST', body });
  assert.equal(first.status, 201);
  assert.equal(first.data.seatingMode, 'choice');
  assert.equal((await f.request(`/api/events/${first.data.id}`, { token: owner.token })).data.seating.seatCount, 12);
  const overlap = await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, title: 'Пересечение', date: plusHours(date, 3) } });
  assert.equal(overlap.status, 409);
  assert.match(overlap.data.error, /забронирован/);
  assert.doesNotMatch(overlap.data.error, /Первый банкет/);
  assert.match(overlap.data.error, /\d{2}:\d{2}/);
  assert.equal((await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, title: 'Следующий', date: plusHours(date, 4) } })).status, 201);
  const secondHall = await f.request(`/api/restaurants/${restaurant.id}/halls`, { token: admin.token, method: 'POST', body: { name: 'Малый зал', capacity: 10, windows: restaurant.halls[0].windows, seatingConfig: { type: 'fixed', fixedLayout: generateLayout('rounds', 10), tablePresets: restaurant.halls[0].seatingConfig.tablePresets } } });
  assert.equal(secondHall.status, 201);
  assert.equal((await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, hallId: secondHall.data.id } })).status, 409);
  assert.equal((await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, hallId: secondHall.data.id, expectedGuests: 8, seating: { mode: 'fixed', template: 'rounds' } } })).status, 403);
  assert.equal((await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, hallId: secondHall.data.id, expectedGuests: 8, seating: { mode: 'fixed' } } })).status, 201);
  const day = date.slice(0, 10);
  const availability = await f.request(`/api/restaurants/${restaurant.id}/availability?date=${day}&hallId=${restaurant.halls[0].id}`, { token: owner.token });
  assert.equal(availability.status, 200);
  assert.equal(availability.data[0].booked.length, 2);
  const month = day.slice(0, 7);
  const slots = await f.request(`/api/restaurants/${restaurant.id}/availability/month?month=${month}&hallId=${restaurant.halls[0].id}&durationHours=4`, { token: owner.token });
  assert.equal(slots.status, 200);
  assert.ok(!slots.data.days.find(entry => entry.date === day).slots.includes('12:00'));
  const ownSlots = await f.request(`/api/restaurants/${restaurant.id}/availability/month?month=${month}&hallId=${restaurant.halls[0].id}&durationHours=4&excludeEventId=${first.data.id}`, { token: owner.token });
  assert.ok(ownSlots.data.days.find(entry => entry.date === day).slots.includes('12:00'));
  const outsider = await f.login(300);
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/availability/month?month=${month}&hallId=${restaurant.halls[0].id}&durationHours=4&excludeEventId=${first.data.id}`, { token: outsider.token })).status, 403);
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/availability?date=${day}&hallId=${restaurant.halls[0].id}`, { token: outsider.token })).data[0].booked[0].eventId, undefined);
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/halls/${restaurant.halls[0].id}`, { token: admin.token, method: 'PATCH', body: { capacity: 5 } })).status, 409);
  const shortWindow = restaurant.halls[0].windows.map(window => ({ ...window, end: '14:00' }));
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/halls/${restaurant.halls[0].id}`, { token: admin.token, method: 'PATCH', body: { windows: shortWindow } })).status, 409);
  assert.equal((await f.request(`/api/events/${first.data.id}`, { token: owner.token, method: 'PATCH', body: { expectedRevision: first.data.revision, date: plusHours(date, 2) } })).status, 409);
});

test('a 24/7 hall accepts a banquet across midnight and reports bookings on both days', async t => {
  const f = await fixture(t);
  const admin = await f.login(900);
  const owner = await f.login(100);
  const restaurant = (await f.request('/api/restaurants', { token: admin.token })).data[0];
  const hall = restaurant.halls[0];
  const windows = Array.from({ length: 7 }, (_, weekday) => ({ weekday, start: '00:00', end: '24:00' }));
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/halls/${hall.id}`, { token: admin.token, method: 'PATCH', body: { windows } })).status, 200);
  const day = new Date(Date.now() + 14 * 86400000).toLocaleDateString('sv-SE', { timeZone: 'Europe/Moscow' });
  const date = new Date(`${day}T23:00:00+03:00`).toISOString();
  const weekday = new Date(`${day}T12:00:00+03:00`).getUTCDay();
  assert.equal(f.store.hallWindow({ windows: [{ weekday, start: '00:00', end: '24:00' }] }, date, 1), true);
  assert.equal(f.store.hallWindow({ windows: [{ weekday, start: '00:00', end: '24:00' }] }, date, 2), false);
  const deadline = atNoon(10);
  const body = { title: 'Ночной банкет', restaurantId: restaurant.id, hallId: hall.id, date, deadline, durationHours: 4, expectedGuests: 8, seating: { mode: 'choice', template: 'rounds' } };
  const first = await f.request('/api/events', { token: owner.token, method: 'POST', body });
  assert.equal(first.status, 201);
  const nextDay = new Date(Date.parse(date) + 86400000).toLocaleDateString('sv-SE', { timeZone: 'Europe/Moscow' });
  const availability = await f.request(`/api/restaurants/${restaurant.id}/availability?date=${nextDay}&hallId=${hall.id}`, { token: owner.token });
  assert.equal(availability.data[0].booked[0].eventId, first.data.id);
  assert.equal((await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, title: 'Пересечение ночью', date: plusHours(date, 2) } })).status, 409);
  assert.equal((await f.request('/api/events', { token: owner.token, method: 'POST', body: { ...body, title: 'Следом', date: plusHours(date, 4) } })).status, 201);
  const changedPolicy = await f.request(`/api/restaurants/${restaurant.id}/halls/${hall.id}`, { token: admin.token, method: 'PATCH', body: { seatingConfig: { ...hall.seatingConfig, type: 'fixed' } } });
  assert.equal(changedPolicy.status, 200);
  assert.equal((await f.request(`/api/events/${first.data.id}`, { token: owner.token })).data.seating.mode, 'choice', 'existing event keeps its own seating mode');
});

test('new and existing Petr demos use the live hall configuration and fixed chair map', async t => {
  const f = await fixture(t);
  const admin = await f.login(900);
  const live = (await f.request('/api/restaurants', { token: admin.token })).data.find(item => item.name === 'Петръ');
  const oldDemo = await f.demo({ role: 'organizer' });
  const oldRestaurant = (await f.request('/api/restaurants', { token: oldDemo.token })).data[0];
  assert.equal(oldRestaurant.halls[0].seatingConfig.type, 'flexible');

  const windows = Array.from({ length: 7 }, (_, weekday) => ({ weekday, start: '00:00', end: '24:00' }));
  const seatingConfig = { ...live.halls[0].seatingConfig, type: 'fixed', fixedLayout: generateLayout('rounds', 24) };
  const updated = await f.request(`/api/restaurants/${live.id}/halls/${live.halls[0].id}`, { token: admin.token, method: 'PATCH', body: { capacity: 30, windows, seatingConfig } });
  assert.equal(updated.status, 200);
  const second = await f.request(`/api/restaurants/${live.id}/halls`, { token: admin.token, method: 'POST', body: { name: 'Малый зал', capacity: 12, windows, seatingConfig: { ...seatingConfig, fixedLayout: generateLayout('rounds', 12) } } });
  assert.equal(second.status, 201);

  f.store.transaction(() => f.store.syncDemoPetrHalls());
  const migrated = (await f.request('/api/restaurants', { token: oldDemo.token })).data[0];
  assert.equal(migrated.halls.length, 2);
  assert.equal(migrated.halls[0].id, oldRestaurant.halls[0].id);
  assert.deepEqual(migrated.halls[0].seatingConfig, updated.data.seatingConfig);
  assert.deepEqual(migrated.halls[0].windows, windows);
  const oldEvent = (await f.request('/api/events', { token: oldDemo.token })).data.find(item => item.selectionMode === 'individual');
  const oldDetail = (await f.request(`/api/events/${oldEvent.id}`, { token: oldDemo.token })).data;
  assert.equal(oldDetail.seating.canCustomize, false);
  assert.deepEqual(oldDetail.seating.layout, updated.data.seatingConfig.fixedLayout);
  assert.equal(oldDetail.seating.occupied.length, 3);

  const newDemo = await f.demo({ role: 'organizer' });
  const cloned = (await f.request('/api/restaurants', { token: newDemo.token })).data[0];
  assert.equal(cloned.halls.length, 2);
  assert.notEqual(cloned.halls[0].id, live.halls[0].id);
  assert.deepEqual(cloned.halls.map(hall => hall.seatingConfig), [updated.data.seatingConfig, second.data.seatingConfig]);
  assert.deepEqual(cloned.halls.map(hall => hall.windows), [windows, windows]);
  const newEvent = (await f.request('/api/events', { token: newDemo.token })).data.find(item => item.selectionMode === 'individual');
  const newDetail = (await f.request(`/api/events/${newEvent.id}`, { token: newDemo.token })).data;
  assert.equal(newDetail.seating.canCustomize, false);
  assert.deepEqual(newDetail.seating.layout, updated.data.seatingConfig.fixedLayout);
});

test('restaurant fixed chair map is copied to banquets; only approved table sizes can be arranged', async t => {
  const f = await fixture(t);
  const admin = await f.login(900);
  const organizer = await f.login(100);
  const guest = await f.login(200);
  const restaurant = (await f.request('/api/restaurants', { token: organizer.token })).data[0];
  const fixedLayout = validateLayout(generateLayout('u', 8)).layout;
  const createdHall = await f.request(`/api/restaurants/${restaurant.id}/halls`, { token: admin.token, method: 'POST', body: { name: 'Зал со стандартной схемой', capacity: 20, windows: restaurant.halls[0].windows, seatingConfig: { type: 'fixed', fixedLayout, tablePresets: restaurant.halls[0].seatingConfig.tablePresets } } });
  assert.equal(createdHall.status, 201);
  const hall = createdHall.data;
  assert.equal(hall.allowFreeSeating, false);
  assert.deepEqual(hall.seatingConfig.fixedLayout, fixedLayout);
  const body = { title: 'Стандартная рассадка', restaurantId: restaurant.id, hallId: hall.id, date: atNoon(14), deadline: atNoon(10), expectedGuests: 8 };
  const created = await f.request('/api/events', { token: organizer.token, method: 'POST', body });
  assert.equal(created.status, 201);
  const eventId = created.data.id;
  const detail = (await f.request(`/api/events/${eventId}`, { token: organizer.token })).data;
  assert.equal(detail.seating.mode, 'choice');
  assert.equal(detail.seating.canCustomize, false);
  assert.deepEqual(detail.seating.layout, fixedLayout);
  assert.equal((await f.request('/api/events', { token: organizer.token, method: 'POST', body: { ...body, title: 'Чужая схема', date: atNoon(15), seating: { mode: 'fixed', template: 'rounds' } } })).status, 403);
  const noSeating = await f.request('/api/events', { token: organizer.token, method: 'POST', body: { ...body, title: 'Без рассадки', date: atNoon(18), seating: { mode: 'off' } } });
  assert.equal(noSeating.status, 201);
  assert.equal((await f.request(`/api/events/${noSeating.data.id}`, { token: organizer.token })).data.seating.mode, 'off');
  assert.deepEqual((await f.request(`/api/events/${noSeating.data.id}`, { token: organizer.token })).data.seating.layout, fixedLayout);
  assert.equal((await f.request(`/api/events/${eventId}/seating`, { token: organizer.token, method: 'PUT', body: { layout: fixedLayout } })).status, 403);
  assert.equal((await f.request(`/api/events/${eventId}/seating`, { token: organizer.token, method: 'PUT', body: { mode: 'fixed' } })).status, 200);
  const invited = await f.request(`/api/events/${eventId}/guests`, { token: organizer.token, method: 'POST', body: { name: 'Гость', phone: '+79990000123' } });
  assert.equal(invited.status, 201);
  assert.equal((await f.request(`/api/events/${eventId}/seating/assignments`, { token: organizer.token, method: 'PUT', body: { guest: `invite:${invited.data.id}`, seatId: 't1-1' } })).status, 200);
  await f.inviteGuest(organizer.token, created.data, guest.token, 200, '+79990000200', 'Другой гость');
  assert.equal((await f.request(`/api/events/${eventId}/seat`, { token: guest.token, method: 'PUT', body: { seatId: 't1-2' } })).status, 409);
  assert.equal((await f.request(`/api/events/${eventId}/seating`, { token: organizer.token, method: 'PUT', body: { mode: 'choice' } })).status, 200);
  assert.equal((await f.request(`/api/events/${eventId}/seat`, { token: guest.token, method: 'PUT', body: { seatId: 't1-2' } })).status, 200);
  const turnedOff = await f.request(`/api/events/${eventId}/seating`, { token: organizer.token, method: 'PUT', body: { mode: 'off' } });
  assert.equal(turnedOff.status, 200);
  assert.deepEqual(turnedOff.data.occupied, []);
  assert.deepEqual(turnedOff.data.layout, fixedLayout);
  assert.equal((await f.request(`/api/events/${eventId}/seat`, { token: guest.token, method: 'PUT', body: { seatId: 't1-2' } })).status, 409);
  assert.equal((await f.request(`/api/events/${eventId}/seating/assignments`, { token: organizer.token, method: 'PUT', body: { guest: `invite:${invited.data.id}`, seatId: 't1-1' } })).status, 409);
  assert.equal((await f.request(`/api/events/${eventId}/seating`, { token: organizer.token, method: 'PUT', body: { mode: 'fixed' } })).status, 200);
  assert.equal((await f.request(`/api/events/${eventId}/seating/assignments`, { token: organizer.token, method: 'PUT', body: { guest: `invite:${invited.data.id}`, seatId: 't1-1' } })).status, 200);
  const movable = await f.request('/api/events', { token: organizer.token, method: 'POST', body: { ...body, title: 'Смена зала', hallId: restaurant.halls[0].id, date: atNoon(16), seating: { mode: 'fixed', template: 'rounds' } } });
  assert.equal(movable.status, 201);
  const moved = await f.request(`/api/events/${movable.data.id}`, { token: organizer.token, method: 'PATCH', body: { expectedRevision: movable.data.revision, hallId: hall.id } });
  assert.equal(moved.status, 200);
  assert.deepEqual((await f.request(`/api/events/${movable.data.id}`, { token: organizer.token })).data.seating.layout, fixedLayout);
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/halls/${hall.id}`, { token: guest.token, method: 'PATCH', body: { defaultSeatingTemplate: 'long' } })).status, 403);
  assert.equal((await f.request(`/api/restaurants/${restaurant.id}/halls/${hall.id}`, { token: admin.token, method: 'PATCH', body: { seatingConfig: { ...hall.seatingConfig, type: 'flexible', tablePresets: [{ shape: 'round', seats: 4 }] } } })).status, 200);
  const unchanged = (await f.request(`/api/events/${eventId}`, { token: organizer.token })).data;
  assert.equal(unchanged.seating.canCustomize, false, 'existing banquet keeps the restaurant map');
  const flexible = await f.request('/api/events', { token: organizer.token, method: 'POST', body: { ...body, title: 'Новая схема', date: atNoon(17), seating: { mode: 'choice' } } });
  assert.equal(flexible.status, 201);
  assert.equal((await f.request(`/api/events/${flexible.data.id}/seating`, { token: organizer.token, method: 'PUT', body: { mode: 'choice', layout: fixedLayout } })).status, 400);
  const allowedLayout = validateLayout(generateLayout('rounds', 4)).layout;
  assert.equal((await f.request(`/api/events/${flexible.data.id}/seating`, { token: organizer.token, method: 'PUT', body: { mode: 'choice', layout: allowedLayout } })).status, 200);
});

test('package-only dishes have their own KBJU and snapshots stay stable after editing', async t => {
  const f = await fixture(t);
  const admin = await f.login(900);
  const petr = (await f.request('/api/restaurants', { token: admin.token })).data.find(restaurant => restaurant.name === 'Петръ');
  const temp = (await f.request('/api/restaurants', { token: admin.token })).data.find(restaurant => restaurant.name === 'Temp');
  assert.ok(temp.menu.some(item => item.name === 'Буррата с томатами'));
  assert.ok(!petr.menu.some(item => item.name === 'Буррата с томатами'));
  assert.ok(petr.packageDishes.length > 0);
  assert.ok(petr.packages.every(offer => offer.items.every(item => item.dishId && item.nutrition)));
  const created = await f.request(`/api/restaurants/${petr.id}/package-dishes`, { token: admin.token, method: 'POST', body: { name: 'Индейка с овощами', category: 'Горячее', description: 'Для пакета', weight: '250 г', nutrition: { kcal: 330, protein: 40, fat: 9, carbs: 18 }, photoUrl: '', allergens: [], vegetarian: false, labels: ['Много белка'], available: true } });
  assert.equal(created.status, 201);
  assert.equal(created.data.packageOnly, true);
  const offer = await f.request(`/api/restaurants/${petr.id}/packages`, { token: admin.token, method: 'POST', body: { name: 'Пакет с индейкой', description: 'Ужин', price: 250000, items: [{ dishId: created.data.id, grams: 250, choiceGroup: '' }] } });
  assert.equal(offer.status, 201);
  assert.equal(offer.data.items[0].nutrition.protein, 40);
  const event = await f.request('/api/events', { token: admin.token, method: 'POST', body: { title: 'Ужин', restaurantId: petr.id, date: atNoon(14), deadline: atNoon(10), expectedGuests: 3, selectionMode: 'package', packageId: offer.data.id } });
  assert.equal(event.status, 201);
  assert.equal(event.data.package.items[0].nutrition.protein, 40);
  assert.equal((await f.request(`/api/restaurants/${petr.id}/package-dishes/${created.data.id}`, { token: admin.token, method: 'PATCH', body: { nutrition: { kcal: 360, protein: 45, fat: 10, carbs: 18 } } })).status, 200);
  const packagePhoto = '/api/media/00000000-0000-0000-0000-000000000006.jpg';
  assert.equal((await f.request(`/api/restaurants/${petr.id}/package-dishes/${created.data.id}`, { token: admin.token, method: 'PATCH', body: { photoUrl: packagePhoto } })).status, 200);
  const detail = await f.request(`/api/events/${event.data.id}`, { token: admin.token });
  assert.equal(detail.data.event.package.items[0].nutrition.protein, 40);
  assert.equal(detail.data.event.package.items[0].photoUrl, packagePhoto);
  assert.equal((await f.request(`/api/restaurants/${petr.id}/package-dishes/${created.data.id}`, { token: admin.token, method: 'DELETE' })).status, 409);
  const latest = (await f.request('/api/restaurants', { token: admin.token })).data.find(restaurant => restaurant.id === petr.id);
  assert.ok(!latest.menu.some(item => item.id === created.data.id));
});

test('moving legacy test dishes from Petr to Temp keeps existing approved order prices', async t => {
  const { mkdtemp, rm } = await import('node:fs/promises');
  const { tmpdir } = await import('node:os');
  const { join } = await import('node:path');
  const { Store } = await import('../server/store.mjs');
  const directory = await mkdtemp(join(tmpdir(), 'banquet-migrate-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const config = { databasePath: join(directory, 'db.sqlite'), demoEnabled: true, restaurantAdminIds: ['900'], publicUrl: 'https://banquet.example', maxDemoSpaces: 10 };
  const old = new Store(config);
  const owner = old.authenticate(old.loginMax({ id: '900', name: 'Администратор' }).token);
  const petr = old.db.prepare("SELECT id FROM restaurants WHERE name='Петръ'").get();
  const sample = JSON.parse(old.db.prepare("SELECT data FROM menu_items WHERE restaurant_id=(SELECT id FROM restaurants WHERE name='Тёплый вечер') AND json_extract(data,'$.name')='Буррата с томатами'").get().data);
  const sampleId = 'legacy_sample';
  old.db.prepare('INSERT INTO menu_items VALUES (?,?,?)').run(sampleId, petr.id, JSON.stringify({ ...sample, id: sampleId }));
  const event = old.transaction(() => old.createEvent(owner, { title: 'Старый заказ', restaurantId: petr.id, date: atNoon(14), deadline: atNoon(10), expectedGuests: 1 }));
  old.db.prepare('INSERT INTO guests VALUES (?,?,1,?,?)').run(event.id, owner.id, '', new Date().toISOString());
  old.db.prepare('INSERT INTO selections VALUES (?,?,?,?,?,?)').run(event.id, owner.id, sampleId, 2, sample.price, sample.name);
  old.db.prepare("UPDATE events SET status='approved' WHERE id=?").run(event.id);
  const before = old.presentEvent(old.eventRow(event.id, owner), owner).total;
  old.db.exec('PRAGMA user_version=10');
  old.close();
  const migrated = new Store(config);
  t.after(() => migrated.close());
  assert.equal(migrated.db.prepare('SELECT restaurant_id FROM menu_items WHERE id=?').get(sampleId).restaurant_id, migrated.db.prepare("SELECT id FROM restaurants WHERE name='Temp'").get().id);
  const changed = JSON.parse(migrated.db.prepare('SELECT data FROM event_menu WHERE event_id=? AND item_id=?').get(event.id, sampleId).data);
  assert.equal(changed.name, 'Капрезе с помидорами и базиликом');
  assert.equal(changed.price, sample.price);
  const currentOwner = migrated.db.prepare('SELECT * FROM users WHERE id=?').get(owner.id);
  assert.equal(migrated.presentEvent(migrated.eventRow(event.id, currentOwner), currentOwner).total, before);
});
